// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// vwCpp
List vwCpp(std::string training_data, std::string validation_data, std::string validation_labels, std::string out_probs, std::string model, std::string loss, std::string link_function, int b, float learning_rate, int passes, bool do_evaluation);
RcppExport SEXP _rvwCpp_vwCpp(SEXP training_dataSEXP, SEXP validation_dataSEXP, SEXP validation_labelsSEXP, SEXP out_probsSEXP, SEXP modelSEXP, SEXP lossSEXP, SEXP link_functionSEXP, SEXP bSEXP, SEXP learning_rateSEXP, SEXP passesSEXP, SEXP do_evaluationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type training_data(training_dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type validation_data(validation_dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type validation_labels(validation_labelsSEXP);
    Rcpp::traits::input_parameter< std::string >::type out_probs(out_probsSEXP);
    Rcpp::traits::input_parameter< std::string >::type model(modelSEXP);
    Rcpp::traits::input_parameter< std::string >::type loss(lossSEXP);
    Rcpp::traits::input_parameter< std::string >::type link_function(link_functionSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    Rcpp::traits::input_parameter< float >::type learning_rate(learning_rateSEXP);
    Rcpp::traits::input_parameter< int >::type passes(passesSEXP);
    Rcpp::traits::input_parameter< bool >::type do_evaluation(do_evaluationSEXP);
    rcpp_result_gen = Rcpp::wrap(vwCpp(training_data, validation_data, validation_labels, out_probs, model, loss, link_function, b, learning_rate, passes, do_evaluation));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rvwCpp_vwCpp", (DL_FUNC) &_rvwCpp_vwCpp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_rvwCpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
