# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vwCpp <- function(training_data, validation_data, validation_labels, out_probs = "preds.vw", model = "mdl.vw", loss = "logistic", link_function = "logistic", b = 25L, learning_rate = 0.5, passes = 1L, do_evaluation = TRUE) {
    .Call(`_rvwCpp_vwCpp`, training_data, validation_data, validation_labels, out_probs, model, loss, link_function, b, learning_rate, passes, do_evaluation)
}

